### ISSUE TITLE
Namespace is redundant in the ConsolePlugin CR as ConsolePlugin has cluster scope

### ISSUE THREAD

**Issue by empovit** [openshift/console-plugin-template#72]
As `ConsolePlugin` has cluster scope, namespace in _charts/openshift-console-plugin/templates/consoleplugin.yaml_ is redundant and might be confusing:

```
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: {{ template "openshift-console-plugin.name" . }}
  namespace: {{ .Release.Namespace }}
```
